spring:
  profiles:
    active:
      - dev
  thymeleaf:
    prefix:  classpath:/templates/
    spring.thymeleaf.content-type: text/html

    spring.thymeleaf.cache: false

    spring.thymeleaf.mode: LEGACYHTML5





